
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	
	private global::Gtk.Action FileAction;
	
	private global::Gtk.Action HelpAction;
	
	private global::Gtk.Action AboutAction;
	
	private global::Gtk.Action QuitAction;
	
	private global::Gtk.Action HelpAction1;
	
	private global::Gtk.Action AboutUSAction;
	
	private global::Gtk.Action AboutAppAction;
	
	private global::Gtk.Fixed fixed1;
	
	private global::Gtk.MenuBar menubar1;
	
	private global::Gtk.Button SearchButton;
	
	private global::Gtk.Entry entry1;
	
	private global::Gtk.ScrolledWindow scrolledwindow2;
	
	private global::Gtk.Label result;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
		w1.Add (this.FileAction, null);
		this.HelpAction = new global::Gtk.Action ("HelpAction", global::Mono.Unix.Catalog.GetString ("Help"), null, null);
		this.HelpAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Help");
		w1.Add (this.HelpAction, null);
		this.AboutAction = new global::Gtk.Action ("AboutAction", global::Mono.Unix.Catalog.GetString ("About"), null, null);
		this.AboutAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("About");
		w1.Add (this.AboutAction, null);
		this.QuitAction = new global::Gtk.Action ("QuitAction", global::Mono.Unix.Catalog.GetString ("Quit"), null, null);
		this.QuitAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Quit");
		w1.Add (this.QuitAction, null);
		this.HelpAction1 = new global::Gtk.Action ("HelpAction1", global::Mono.Unix.Catalog.GetString ("Help"), null, null);
		this.HelpAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("Help");
		w1.Add (this.HelpAction1, null);
		this.AboutUSAction = new global::Gtk.Action ("AboutUSAction", global::Mono.Unix.Catalog.GetString ("About US"), null, null);
		this.AboutUSAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("About US");
		w1.Add (this.AboutUSAction, null);
		this.AboutAppAction = new global::Gtk.Action ("AboutAppAction", global::Mono.Unix.Catalog.GetString ("About App"), null, null);
		this.AboutAppAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("About App");
		w1.Add (this.AboutAppAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.UIManager.AddUiFromString ("<ui><menubar name='menubar1'><menu name='FileAction' action='FileAction'><menuitem name='QuitAction' action='QuitAction'/></menu><menu name='HelpAction' action='HelpAction'><menuitem name='HelpAction1' action='HelpAction1'/></menu><menu name='AboutAction' action='AboutAction'><menuitem name='AboutUSAction' action='AboutUSAction'/><menuitem name='AboutAppAction' action='AboutAppAction'/></menu></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
		this.menubar1.WidthRequest = 442;
		this.menubar1.Name = "menubar1";
		this.fixed1.Add (this.menubar1);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.menubar1]));
		w2.X = 5;
		w2.Y = 4;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.SearchButton = new global::Gtk.Button ();
		this.SearchButton.WidthRequest = 85;
		this.SearchButton.CanFocus = true;
		this.SearchButton.Name = "SearchButton";
		this.SearchButton.UseUnderline = true;
		this.SearchButton.Label = global::Mono.Unix.Catalog.GetString ("Search");
		this.fixed1.Add (this.SearchButton);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.SearchButton]));
		w3.X = 360;
		w3.Y = 31;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.entry1 = new global::Gtk.Entry ();
		this.entry1.WidthRequest = 348;
		this.entry1.CanFocus = true;
		this.entry1.Name = "entry1";
		this.entry1.IsEditable = true;
		this.entry1.InvisibleChar = '•';
		this.fixed1.Add (this.entry1);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.entry1]));
		w4.X = 5;
		w4.Y = 33;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.scrolledwindow2 = new global::Gtk.ScrolledWindow ();
		this.scrolledwindow2.WidthRequest = 433;
		this.scrolledwindow2.HeightRequest = 442;
		this.scrolledwindow2.CanFocus = true;
		this.scrolledwindow2.Name = "scrolledwindow2";
		this.scrolledwindow2.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child scrolledwindow2.Gtk.Container+ContainerChild
		global::Gtk.Viewport w5 = new global::Gtk.Viewport ();
		w5.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child GtkViewport.Gtk.Container+ContainerChild
		this.result = new global::Gtk.Label ();
		this.result.Name = "result";
		w5.Add (this.result);
		this.scrolledwindow2.Add (w5);
		this.fixed1.Add (this.scrolledwindow2);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.scrolledwindow2]));
		w8.X = 6;
		w8.Y = 65;
		this.Add (this.fixed1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 454;
		this.DefaultHeight = 514;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.QuitAction.Activated += new global::System.EventHandler (this.onQuit);
		this.HelpAction1.Activated += new global::System.EventHandler (this.onHelp);
		this.SearchButton.Clicked += new global::System.EventHandler (this.onSearch);
		this.entry1.Activated += new global::System.EventHandler (this.onEntered);
	}
}
